# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: build
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      -name: Download dark-cli
        run: |
          curl -O https://dark-cli.storage.googleapis.com/latest/dark-cli-linux
          chmod +x ./dark-cli-linux

      - name: Download build dir
        uses: actions/download-artifact@v2
        with:
          name: build-dir
    
      - name: Deploy to Dark
        env:
          DARK_CLI_USER: ${{ secrets.DARK_CLI_USER }}
          DARK_CLI_PASSWORD: ${{ secrets.DARK_CLI_PASSWORD }}
          DARK_CLI_CANVAS: ${{ secrets.DARK_CLI_CANVAS }}
        run: dark-cli-linux build --canvas $DARK_CLI_CANVAS
